name: "Project Issue"
description: "Log a project issue (problem, decision, request)"
title: "[ISSUE] <short summary>"
labels:
  - type::issue
  - status::open
body:
  - type: input
    id: issue_id
    attributes:
      label: Issue ID
      description: "Unique identifier (e.g., 2024/XX)"
      placeholder: "2024/XX"

  - type: dropdown
    id: field
    attributes:
      label: Field
      options:
        - Geometry
        - Digitize
        - Reconstruct
        - Analyze
        - Core Software
        - Interfaces
        - Grain
        - EdepSim
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: Type / Priority
      options:
        - MINOR
        - MAJOR

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Describe the issue clearly"
      placeholder: "What is the problem or request?"

  - type: textarea
    id: impact
    attributes:
      label: Impact
      placeholder: "Describe consequences or risks (if known)"

  - type: input
    id: actionee
    attributes:
      label: Issue Owner(s)
      placeholder: "Name(s) of responsible people"

  - type: input
    id: due_date
    attributes:
      label: Target Resolution Date
      placeholder: "YYYY-MM-DD"

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Pending
        - In Progress
        - Completed
        - Blocked
        - Closed

  - type: textarea
    id: activities
    attributes:
      label: Activities Carried Out
      placeholder: "Progress, logs, or completed steps"

  - type: textarea
    id: outcome
    attributes:
      label: Outcome / Results / Challenges / Lessons Learned
      placeholder: "Describe findings and challenges"

  - type: textarea
    id: next_steps
    attributes:
      label: Next Steps / Follow-up Actions
      placeholder: "Describe follow-up work"
