name: Task
description: Create a new task, issue, or action
title: "[TASK] <short description>"
labels: ["type:task", "status:to-do"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the task or action
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Add context, links, or subtasks
  - type: input
    id: due_date
    attributes:
      label: Due date
  - type: input
    id: actionee
    attributes:
      label: Responsible person
